add cve-2020-13945 vulnerability environment
google/security-testbeds pull request #80
Opened 2024-08-04 10:51 UTC by hh-hunter

@tooryx This is about the vulnerability environment submission for Apache APISIX(CVE-2020-13945).

2024-08-13 18:51 UTC, lokiuox commented
Hey @hh-hunter , please implement the following changes:
- Rename the files according to the changes requested in [this comment](https://github.com/google/tsunami-security-scanner-plugins/pull/523#pullrequestreview-2236227030)
- Add an example safe configuration (e.g. with a non-default admin API key).

2024-08-16 09:51 UTC, hh-hunter commented
Hey, I have fixed these problems, please review

2024-09-21 17:15 UTC, lokiuox requested changes
Hey @hh-hunter, here are a few small suggestions. Also please delete the old directory, i.e. `apache/apisix/CVE-2020-13945`. Besides these the testbed is fine.

2024-09-21 17:15 UTC, lokiuox commented on apache/apisix/Default_api_token/docker-compose-non-vulnerable.yml
> +version: "3.9"
```suggestion
```
Version is deprecated

2024-09-21 17:15 UTC, lokiuox commented on apache/apisix/Default_api_token/docker-compose.yml
> +version: "3.9"
```suggestion
```
Version is deprecated

2024-09-21 17:15 UTC, lokiuox commented on apache/apisix/Default_api_token/README.md
> +The container that is not affected by the vulnerability is `apache-apisix-defaul-api-token-safe`,you can use it `docker-compose -f docker-compose-safe.yml up -d` to start the container, and the servi
```suggestion
You can start the vulnerable service by running the command `docker compose up -d`. The deployed container has name `apache-apisix-defaul-api-token` and listens on port `9080`.

The container that is not affected by the vulnerability is `apache-apisix-defaul-api-token-safe`, you can start it with `docker compose -f docker-compose-safe.yml up -d`, and the service listens on port `9081`.
```
A small wording suggestion

2024-09-21 17:45 UTC, lokiuox approved these changes
Thanks, I think this is good to go.

2024-09-21 17:46 UTC, hh-hunter commented
It's done. @lokiuox

2024-10-22 12:47 UTC, tooryx approved these changes

2024-10-22 22:36 UTC, merged