testbed for  Joomla Improper AccessCheck in WebService Endpoint
google/security-testbeds pull request #92
Opened 2024-10-19 10:35 UTC by am0o0

hello, this is according to the @leonardo-doyensec request in this issue:
https://github.com/google/tsunami-security-scanner-plugins/pull/529

2024-10-25 15:06 UTC, lokiuox requested changes
Hi @am0o0, thanks for your contribution!

I confirm the testbed is working, I've left a few comments on a few very minor improvements.

2024-10-25 15:06 UTC, lokiuox commented on joomla/CVE-2023-23752/docker-compose-safe.yml
> +    restart: always
```suggestion
```
Let's remove the `restart` so the container doesn't accidentally restart by itself after the test.

2024-10-25 15:06 UTC, lokiuox commented on joomla/CVE-2023-23752/docker-compose-safe.yml
> +    restart: always
```suggestion
```
Let's remove the `restart` so the container doesn't accidentally restart by itself after the test.

2024-10-25 15:06 UTC, lokiuox commented on joomla/CVE-2023-23752/docker-compose-vulnerable.yml
> +    restart: always
```suggestion
```
Let's remove the `restart` so the container doesn't accidentally restart by itself after the test.

2024-10-25 15:06 UTC, lokiuox commented on joomla/CVE-2023-23752/docker-compose-vulnerable.yml
> +    restart: always
```suggestion
```
Let's remove the `restart` so the container doesn't accidentally restart by itself after the test.

2024-11-21 14:10 UTC, lokiuox approved these changes
Thanks, LGTM.

2024-11-21 18:43 UTC, lokiuox commented on joomla/CVE-2023-23752/docker-compose-safe.yml
> +services:
```suggestion
name: joomla-cve-2023-23752-safe
services:
```

2024-11-21 18:43 UTC, lokiuox commented on joomla/CVE-2023-23752/docker-compose-vulnerable.yml
> +services:
```suggestion
name: joomla-cve-2023-23752-vulnerable
```

2024-11-25 19:10 UTC, lokiuox approved these changes
LGTM.

2024-11-27 13:34 UTC, tooryx approved these changes

2026-02-18 14:35 UTC, closed without merging